import Head from 'next/head'
import Image from 'next/image'
import Feed from '../Components/Feed'
import Header from '../Components/Header'
import UploadModal from '../Components/UploadModal'

export default function Home() {
  return (
    <div className='bg-gray-50 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Feed/>
      {/* modal */}
      <UploadModal/>
    </div>
  )
}
